name: RelaxAutoCompressor
version: '1.2.9'
main: org.ReleaxBoxAutoComp.relaxAutoCompressor.RelaxAutoCompressor
api-version: '1.21'
authors: [ Nerd Bear ]
description: A general plugin to display my skill and ability in making plugins
website: nerd-bear.org
